[package]
name = "rust-faker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
fake = { version = "2.9", features = ["derive"] }
rand = "0.8"
csv = "1.3"
indicatif = "0.17"

[dev-dependencies]
tempfile = "3.10"
